apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    deployment:
      kind: DaemonSet
    nodeSelector:
      node-role.smp.am/worker: "true"
    service:
      type: ClusterIP
    hostNetwork: true
    ports:
      web:
        port: 80
      websecure:
        port: 443
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 2
        maxSurge: 0
