apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: smart-rest-php-fpm
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: smart-rest
      app.kubernetes.io/component: php-fpm
