apiVersion: v1
kind: ResourceQuota
metadata:
  name: smart-rest-quota
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "30"
    services: "10"
    secrets: "30"
    configmaps: "30"

