apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-rest-local
resources:
  - ../../../prod/apps/smart-rest
patches:
  - path: namespace.patch.yaml
  - path: deployment.patch.yaml
  - path: deployment-php-fpm.patch.yaml
  - path: ingress.patch.yaml
  - path: resourcequota.patch.yaml
  - path: hpa.patch.yaml
  - path: hpa-php-fpm.patch.yaml
  - path: networkpolicy.patch.yaml
  - path: nginx-egress-networkpolicy.patch.yaml
  - path: ingress-networkpolicy.patch.yaml
